### ISSUE TITLE
Quant Data Analysis

### ISSUE THREAD

**Issue by alexsb** [visdesignlab/UpSet-Survey-ReVISit--Data-Analysis#4]
We want the following things: 

* [x] Correctness by condition #7 
* [x] Correctness by question and by condition #9 
* [x] Time by condition #16 
* [x] Preferences #12 
* [x] Confidence / understanding / effectiveness by condition  #15
